### ISSUE TITLE
Projects with no log4j2 Routing appender produce error

### ISSUE THREAD

**Issue by TrueWill** [UFGInsurance/mulint#45]
When I run mulint on a project that doesn’t have database logging enabled (No routing appender) I am getting exceptions:
```
/Development/Projects/mulint/validateLog4j.js:67
 let databaseRoute = xml.Configuration.Appenders[0].Routing[0].Routes[0].Route.find(
                                                           ^

TypeError: Cannot read property ‘0’ of undefined
   at validateLog4j (/Development/Projects/mulint/validateLog4j.js:67:61)
   at Command.program.version.description.arguments.on.action.apiBasePath (/Development/Projects/mulint/mulint.js:40:5)
   at Command.listener (/Development/Projects/mulint/node_modules/commander/index.js:315:8)
   at Command.emit (events.js:182:13)
   at Command.parseArgs (/Development/Projects/mulint/node_modules/commander/index.js:653:12)
   at Command.parse (/Development/Projects/mulint/node_modules/commander/index.js:474:21)
   at Object.<anonymous> (/Development/Projects/mulint/mulint.js:44:4)
   at Module._compile (internal/modules/cjs/loader.js:689:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
   at Module.load (internal/modules/cjs/loader.js:599:32)
```

Pretty easy to replicate. Edit a log4j2.xml file. Remove the “Routing” element and change the appender-ref to “file” instead of “Routing”. Run mulint on the project.

(From @aoathout )

**Comment by TrueWill** [comment]
Discussed with @aoathout ; we decided to remove the database logging checks altogether rather than make them optional.
